name: Release
  
# for debug
on: push

# on:
#   push:
#     tags:
#       - 'v*'

jobs:
  build:
    strategy:
      matrix:
        targets:
          - target: x86_64-apple-darwin
            os: macos-14
          - target: aarch64-apple-darwin
            os: macos-14
    defaults:
      run:
        working-directory: rs
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: rustup target add ${{ matrix.targets.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.targets.target }}
      - name: test
        run: |
          pwd
          ls -lah
          ls -lah target
          ls -lah target/${{ matrix.targets.target }}
          ls -lah target/${{ matrix.targets.target }}/release
      - name: Archive
        run: tar -czf rs-${GITHUB_REF_NAME#v}-${{ matrix.targets.target }}.tar.gz target/${{ matrix.targets.target }}/release/rs
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: rs-${GITHUB_REF_NAME#v}-${{ matrix.targets.target }}.tar.gz
  download:
    strategy:
      matrix:
        targets:
          - target: x86_64-apple-darwin
            os: macos-14
          - target: aarch64-apple-darwin
            os: macos-14
    runs-on: ${{ matrix.targets.os }}
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release
          path: rs-${GITHUB_REF_NAME#v}-${{ matrix.targets.target }}.tar.gz
      - name: Print checksum
        run: shasum -a 256 rs-${GITHUB_REF_NAME#v}-${{ matrix.targets.target }}.tar.gz
  # release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Write release version
  #       run: |
  #         VERSION=${GITHUB_REF_NAME#v}
  #         echo Version: "${VERSION}", GitHub Ref Name: "${GITHUB_REF_NAME}"
  #         echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
  #     - name: Read version
  #       run: |
  #         echo Version: "${VERSION}"
  #     - name: Create Draft Release
  #       uses: softprops/action-gh-release@v2.0.1
  #       with:
  #         draft: true
  #         generate_release_notes: true
  #         make_latest: "true" # string...??
  #         files: |
  #           README.md
  #           ./rs/Cargo.toml
  #           ./go/go.mod