name: Rust Release
  
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        targets:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-14
          - target: aarch64-apple-darwin
            os: macos-14
    defaults:
      run:
        working-directory: rs
    runs-on: ${{ matrix.targets.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: rustup target add ${{ matrix.targets.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.targets.target }}
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> ${GITHUB_ENV}
      - name: Archive
        run: tar -czf rs-${{ env.RELEASE_VERSION }}-${{ matrix.targets.target }}.tar.gz -C target/${{ matrix.targets.target }}/release rs
      - name: Checksum
        run: shasum -a 256 rs-${{ env.RELEASE_VERSION }}-${{ matrix.targets.target }}.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.targets.target }}
          path: rs/rs-${{ env.RELEASE_VERSION }}-${{ matrix.targets.target }}.tar.gz # working-directory 設定を見てくれないらしい...
          if-no-files-found: error
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: releases
          pattern: release-*
          merge-multiple: true
      - name: Checksum
        run: sha256sum releases/* > ./releases/checksum.txt
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.0.1
        with:
          draft: true
          generate_release_notes: true
          make_latest: true
          files: |
            releases/*