name: Rust build

on:
  push:
    paths:
      - 'rs/**'
  pull_request:
    branches:
      - master
    paths:
      - 'rs/**'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: rs

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --all -- --check
      - name: lint
        run: cargo clippy --all-targets --all-features -- -D warnings
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

